// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iktwmxrnfbfiarmtabsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdHdteHJuZmJmaWFybXRhYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjY2MjAsImV4cCI6MjA3NDY0MjYyMH0.xp8QB5DC0vbEfxJxYve3Paj_0toYeiFNIcs_hCUcTfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});